name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION : "us-east-1"
  ECR_REPOSITORY_NAME: "ammar"
  AWS_ACCOUNT_ID: 489994096722

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/ammar-github-assume-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Pushing to ECR
        run: |
          aws ecr get-login-password --region ${{env.AWS_REGION}} | docker login --username AWS --password-stdin ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com
          docker build -t ${{env.ECR_REPOSITORY_NAME}} .
          IMAGE_TAG=${{ github.run_number }}
          docker tag ${{env.ECR_REPOSITORY_NAME}}:latest ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY_NAME}}:$IMAGE_TAG
          docker push ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY_NAME}}:$IMAGE_TAG
      
      - name: Create Task Defination revision
        run: |
          sed -i 's/NEW_TAG/${{github.run_number}}/g' "task-defination.json"
          task_definition=$(aws ecs register-task-definition --cli-input-json file://task-defination.json)
          task_definition_arn=$(echo $task_definition | jq '.taskDefinition.taskDefinitionArn' | tr -d '"')
          aws ecs update-service --service abr --task-definition $task_definition_arn